site_name: YASH

repo_url: https://bitbucket.org/franckpaul/
# edit_uri: src/default/mkdocs/docs/

site_description: Syntaxe highlighter plugin for Dotclear 2
site_author: Pep and contributors

pages:
- 'Introduction': 'index.md'
- User Guide:
    - 'Usage': 'user-guide/usage.md'
    - 'Settings': 'user-guide/settings.md'
    - 'SyntaxeHL compatibility': 'user-guide/syntaxehl.md'
- 'Release Notes': 'release-notes.md'
- 'About': 'about.md'

# Theme (doc: http://squidfunk.github.io/mkdocs-material/)
theme: material
extra:
  palette:
    primary: 'Deep Purple'
    accent: 'Pink'
  social:
    - type: 'github'
      link: 'https://github.com/franck-paul'
    - type: 'twitter'
      link: 'https://twitter.com/franckpaul'

markdown_extensions:
- extra
- fenced_code
- meta
- smarty
- toc:
    permalink: True
- admonition
- codehilite:
    guess_lang: false
- footnotes
- pymdownx.arithmatex
- pymdownx.betterem(smart_enable=all)
- pymdownx.caret
- pymdownx.critic
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_svg
- pymdownx.inlinehilite
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist(custom_checkbox=true)
- pymdownx.tilde
